### ISSUE TITLE
stop() isn't working 

### ISSUE THREAD

**Issue by Flippo24** [thenativeweb/runfork#4]
Hi, stopping the fork from parent process isn't working for me. The example the readme isn't precise enough. I thought with "await stop();" you are waiting for the fork to finish in your example. 

//my example parrent
const runfork = require('runfork');
const run = runfork({
  path: './child.js'
});

// my expected child stopping function
run.stop()

Why the possibility for sending messages from parrent to child is missing?

**Comment by goloroden** [comment]
> stopping the fork from parent process isn't working for me.

What does "isn't working for me" mean? What happens? What doesn't happen? Is there an error? An error message? …?

> The example the readme isn't precise enough.

What is missing in your opinion?

> I thought with "await stop();" you are waiting for the fork to finish in your example.

Apparently, this was not what happened in your case – so, what happened?

Sorry, but in this form, this bug request is pretty useless, and we can't reproduce anything of what you claim. Please provide an example, and the expected as well as the actual result.

Oh, and regarding your snide remark:

> Why the possibility for sending messages from parrent to child is missing?

Because this is open-source, and we didn't need it so far, and there is no right to demand that a certain feature will be implemented, and especially it's a little bit strange to ask why a certain feature was not implemented so far. Please remember that this is provided for free, on a voluntary base. So if you miss something and are unhappy with the current situation, feel free to implement the missing feature and provide a pull request.

Just complaining will help nobody, only give people who provide to open-source the feeling that what they have done is not good enough.
